### ISSUE TITLE
Zettelkasten-ing

### ISSUE THREAD

**Issue by cogdog** [rtanglao/rtDOTcom#16]
re http://rolandtanglao.com/2021/12/11/p1-zettelkasten-german-scholar-productivity-linked-notes/

Maybe I need to read the link first, but I like knowing this is an established practice. But does it work more as a general guideline or a regular act? And this one mean one could never write a first post ;-)

More just trying, after reading you notes in my reader, what commenting is like.

**Comment by rtanglao** [comment]
`Maybe I need to read the link first, but I like knowing this is an established practice. But does it work more as a general guideline or a regular act? And this one mean one could never write a first post ;-)`
@cogdog regular act! and for first post inception or something :-)
