### ISSUE TITLE
wsl+firefox

### ISSUE THREAD

**Issue by chris2crawford** [rtanglao/rtDOTcom#8]
http://rolandtanglao.com/2019/01/02/p1-howto-make-firefox-work-on-wsl/
I believe this doesn't work anymore on WSL 1 + ubuntu 18.04.2
I couldn't find option "browser.tabs.remote.autostart.2 = false"
and after the other steps, I get the same errors.
--Chris

**Comment by rtanglao** [comment]
hmmmm this still works for me, not sure about browser.tabs.remote.autostart.2.
I will try and find some time to double check!

**Comment by tshirtman** [comment]
yes, i have issues with that as well, the last version of firefox i can get to run is 69.0, (i documented my issues and workarounds in https://github.com/microsoft/WSL/issues/4964 in case it helps anyone), and even with this version, i sometime have really weird behaviors, and i need to kill/restart it, which is often inconvenient. I have the "there is something we need to do" restart page from time to time (but not *all* the time as i had with other versions), and sometime the tab management just stops working (switching tab, opening/closing existing ones), it works good enough 90% of the time though, so i'm putting up with it, but i'd love some better solution.

**Comment by rtanglao** [comment]
hi @chris2crawford  and @tshirtman ! i don't have time to look at this, so closing for now! i'll re-open if i find time!
