### ISSUE TITLE
Definitely hanging out at the coffee house

### ISSUE THREAD

**Issue by emceeaich** [rtanglao/rtDOTcom#9]
I really look forward to sitting out at Chromatic with a cup of :coffee:.

**Comment by rtanglao** [comment]
did you get to Chromatic for outdoor coffee @emceeaich ?

**Comment by rtanglao** [comment]
Since end of May, i've been  going to revolver coffee in Gastown, Vancouver and ordering in the alley window and enjoying their takeout coffee on their steps since their policy is that they won't open until there's a cure/much better test and quicker test

**Comment by emceeaich** [comment]
Chromatic has a large space in Midtown. No seating, but you can get brewed coffee and beans while well-socially-distanced from one another.

**Comment by rtanglao** [comment]
here's hoping emma you and i get innoculated  by april may or june 2021 :-) fingers crossed

**Comment by rtanglao** [comment]
well it looks like you got 2 shots, right @emceeaich? do you feel normal :-)?, has chromatic reopened inside, are you feeling comfortable sitting inside at a café? [i have only had 1 shot](http://rolandtanglao.com/2021/04/08/p1-first-dose-astra-zeneca-covid-19-vaccine-go-science-go/) and it was on April 8th

**Comment by rtanglao** [comment]
i am still only drinking coffee outside @emceeaich ! perhaps someday we'll drink coffee outside revolve Emma! Stay healthy! Closing this issue.
